### ISSUE TITLE
Gradle problem

### ISSUE THREAD

**Issue by ktxdev** [justneon33/1SecMail#1]
![image](https://user-images.githubusercontent.com/38311102/90288730-23bea480-de83-11ea-9f48-925485abc02d.png)

**Comment by ktxdev** [comment]
![image](https://user-images.githubusercontent.com/38311102/90291290-443d2d80-de88-11ea-853b-96b082ab94b4.png)

**Comment by ktxdev** [comment]
Please publish release!

**Comment by y9san9** [comment]
Released `1.0`
