### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ktxdev** [justneon33/1SecMail#2]
![image](https://user-images.githubusercontent.com/38311102/90289808-56699c80-de85-11ea-9dce-af3a3c976db7.png)

**Comment by ktxdev** [comment]
java.lang.IllegalArgumentException: Non-positive period.
 at java.util.Timer.schedule(Timer.java:247)
        at com.unicon.tempomail.mail.TempMail.newMail(TempMail.kt:29)

**Comment by justneon33** [comment]
fixed btw

**Comment by ktxdev** [comment]
When? This error is present in the code.

**Comment by justneon33** [comment]
fixed a few minutes ago

**Comment by ktxdev** [comment]
Now I see, thanks
