### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by ktxdev** [justneon33/1SecMail#3]
![image](https://user-images.githubusercontent.com/38311102/90291997-b6fad880-de89-11ea-96ed-2f8654fbd3fc.png)

**Comment by ktxdev** [comment]
![image](https://user-images.githubusercontent.com/38311102/90292083-e14c9600-de89-11ea-9343-ba0aa44fd483.png)

**Comment by ktxdev** [comment]
Предполагаемое решение:
![image](https://user-images.githubusercontent.com/38311102/90292563-cb8ba080-de8a-11ea-8262-1d5c691e1263.png)

**Comment by ktxdev** [comment]
![image](https://user-images.githubusercontent.com/38311102/90292685-11486900-de8b-11ea-8535-2a392e2780b5.png)

**Possible Solution.**

**Comment by y9san9** [comment]
Is an issue solved ?

**Comment by ktxdev** [comment]
yes
