### ISSUE TITLE
No messages from mail

### ISSUE THREAD

**Issue by ktxdev** [justneon33/1SecMail#4]
![image](https://user-images.githubusercontent.com/38311102/90292927-93389200-de8b-11ea-8d41-dd23ca604efc.png)
No messages from mail

**Comment by justneon33** [comment]
1SecMail don't have api for new mails, in our library "new" messages its only messages which not was loaded in "mailbox" method.

**Comment by ktxdev** [comment]
This doesn't want to work :(

**Comment by ktxdev** [comment]
![image](https://user-images.githubusercontent.com/38311102/90293737-70a77880-de8d-11ea-9873-04cc68f19879.png)

my received messages...

**Comment by justneon33** [comment]
Okey, i will check it later

**Comment by ktxdev** [comment]
api.getMessages(login, domain) always have error

**Comment by justneon33** [comment]
problem fixed.
problem was in 1secmail.com ssl certificate
